[package]
name = "rustychess_core"
version = "0.1.0"
authors = ["Morten Klim Sørensen <mail@kl1m.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.6"
hashbrown = "0.11"
colored = "2"
quick-error = "2.0.1"
chrono = "0.4.24"
regex = "1"
